FROM python:3.11-slim
RUN pip install --no-cache-dir \
        dbt-core==1.8.0 \
        dbt-snowflake==1.8.0 \
        kafka-python==2.0.2 \
        snowflake-connector-python==3.7.1
WORKDIR /usr/app
ENTRYPOINT ["dbt"]
