name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: {python-version: "3.11"}

      - name: Install deps
        run: |
          pip install dbt-core==1.8.0 dbt-snowflake==1.8.0
          pip install apache-airflow==2.10.5 airflow-dag-lint pytest

      - name: dbt deps & build
        run: |
          cd dbt
          dbt deps
          dbt build --select state:modified+

      - name: Lint DAGs
        run: dag-lint dags/

      - name: Unit tests (if any)
        run: pytest -q
