name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dbt-ci:
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create dbt profiles directory
        run: mkdir -p ~/.dbt

      - name: Create profiles.yml for CI
        run: |
          cat > ~/.dbt/profiles.yml << EOF
          spotify:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: $SNOWFLAKE_ACCOUNT
                user: $SNOWFLAKE_USER
                password: $SNOWFLAKE_PASSWORD
                warehouse: $SNOWFLAKE_WAREHOUSE
                database: $SNOWFLAKE_DATABASE
                schema: $SNOWFLAKE_SCHEMA
                threads: 4
                client_session_keep_alive: False
                reuse_connections: True
          EOF

      - name: Run dbt debug
        run: dbt debug --project-dir dbt

      - name: Run dbt models
        run: dbt run --project-dir dbt

      - name: Run dbt tests
        run: dbt test --project-dir dbt